### ISSUE TITLE
Calling call_indirect with argument and with a function defined prior to type definitions will cause exception

### ISSUE THREAD

**Issue by kanaka** [fastly/lucet#158] opened 2019-04-26 03:18 UTC
I discovered a backtrace when calling `call_indirect` in a much more complicated program but simplified it down to the following reproducer:

```
(module $calli

  (table funcref (elem $fn0 $fn1))

  ;; Must have a function before the types to trigger the issue
  (func $early_fn (param $arg i32) (result i32) (i32.const 0))

  (type $fnT0 (func (param i32) (result i32)))
  (type $fnT1 (func (result i32)))

  (func $fn0 (param $arg i32) (result i32) (i32.const 0))
  (func $fn1 (result i32) (i32.const 0))

  (func $main0 (drop (call_indirect (type $fnT0) (i32.const 0) (i32.const 0))))
  (func $main1 (drop (call_indirect (type $fnT1) (i32.const 1))))

  ;; This causes a backtrace
  (export "_start0" (func $main0))

  ;; This does not cause a backtrace
  (export "_start1" (func $main1))

  ;; Default _start (for wasmtime)
  (export "_start" (func $main0))
)
```

Here is how the problem manifests:

```
$ /opt/lucet/bin/lucetc-wasi -o calli.so calli.wasm
$ RUST_BACKTRACE=1 /opt/lucet/bin/lucet-wasi --entrypoint _start0 calli.so
thread 'main' panicked at 'lucet-wasi runtime error: Runtime fault: FaultDetails { fatal: false, trapcode: Some(BadSignature), rip_addr: 139639523104562, rip_addr_details: Some(AddrDetails { in_module_code: true, file_name: Some("/mal/wasm/calli.so"), sym_name: Some("guest_func__start0") }) }', lucet-wasi/src/main.rs:196:23
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:340
   7: lucet_wasi::main
   8: std::rt::lang_start::{{closure}}
   9: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  10: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:92
  11: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  12: main
  13: __libc_start_main
  14: _start
$ RUST_BACKTRACE=1 /opt/lucet/bin/lucet-wasi --entrypoint _start1 calli.so
$ wasmtime calli.wasm
```

Note that calling the `_start1` entrypoint doesn't not cause the problem only calling `_start0` will trigger the problem. Also, wasmtime is able to call the `_start1` entrypoint without issue.

The problem appears to be triggered by a combination of two things. The first is a `call_indirect` call that has an argument to use with the called function (`_start0`). Using call_indirect without the argument does not trigger the issue (`_start1`). The second necessary part to trigger this is that there must be a function (`early_fn`) declared prior to the definition of the two types. If that function is omitted or moved below the type definition then the problem does not reproduce.

**Comment by pchickey** [comment] 2019-04-26 05:49
Oh! I know this one. The icall implementation is incorrect at the moment, and we fail a spec test that demonstrates this exact issue. When we expand the icall instruction, we check the type index at the call site with the type index of the callee. The problem is, multiple type indices can have the same structural type - the `$early_fn` type will be assigned to `$fn0`, which will be a different index than `$fnT0` .

Full spec test compliance is important to us. I think we will achieve it within the next month or two. This issue is pretty isolated from the engineering we're doing to fix the rest of the major spec compliance issues, so I should be able to get a fix in pretty soon.

**Comment by awortman-fastly** [comment] 2019-04-26 16:12
What commit were you on when you ran into this issue? I was somewhat surprised to find this works on master, since there _are_ related spec tests we don't currently pass.

This:
```
(module $calli

  (table funcref (elem $fn0))

  (type $fnT0 (func (param i32) (result i32)))
  (type $fnT1 (func (param i32) (result i32)))

  (func $fn0 (param $arg i32) (result i32) (i32.const 0))

  (func $main0 (drop (call_indirect (type $fnT1) (i32.const 0) (i32.const 0))))

  (export "_start" (func $main0))
)
```
does still erroneously claim `BadSignature`, and that's definitely due to us not checking structural equivalence between `$fnT0` and `$fnT1`. But it's also not the same code you reported :) I'm left wondering what's different that your example seems to run without issue when I tested it..

**Comment by kanaka** [comment] 2019-04-27 00:52
I don't have access to the system where I produced this but I checked out lucet an hour or two before I filed the bug (i.e. yesterday). If you aren't seeing it then I expect it is dependent on the wat -> wasm compiler behavior. I'm using `wasm-as` from binaryen and I'll have to get access to my home workstation before I can figure out what version it is.

**Comment by pchickey** [comment] 2019-04-27 21:00
`lucetc` can accept wat syntax directly, and translates it to wasm using the `wabt` package's translator (also available as the `wat2wasm` executable. So, its probably a difference in how those two translators work.

**Closed** 2019-05-03 22:37 UTC
